name: Build VSIX Package

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # Only run the job when either:
    # - a push to master triggered the workflow, or
    # - the `test.yml` workflow_run completed successfully on master
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Build and package VSIX
        run: npm run vsix
