name: VS Code Extension Tests (headless)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx tsc --project tsconfig.json

      - name: Install Xvfb (for headless Electron)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run extension tests (headless)
        env:
          CI: true
          HEADLESS: 1
        run: |
          # use xvfb-run to provide a virtual display for Electron
          # short user data dir is set by the test runner; just invoke it
          xvfb-run -s "-screen 0 1280x720x24" node ./out/test/runTest.js
